---
- name: Grab a LXD release tarball, and extract the archive
  ansible.builtin.unarchive:
    src: https://github.com/lxc/lxd/releases/download/lxd-{{ lxd_release_version }}/{{ _lxd_extracted_dir }}.tar.gz
    dest: "{{ lxd_extracted_tarball_parent_path }}"
    remote_src: true
    extra_opts:
      - --no-same-owner
  become: true
  when: lxd_src_path | length == 0

- name: Build the LXD libraries
  ansible.builtin.shell:
    chdir: "{{ lxd_src_path | default(lxd_extracted_tarball_parent_path + '/' + _lxd_extracted_dir, true) }}"
    cmd: . "{{ lxd_source_go_env_vars_file_path }}" && make deps
  become: true
  environment:
    - GOPATH: "{{ lxd_source_go_path }}"

- name: Build LXD
  ansible.builtin.shell:
    chdir: "{{ lxd_src_path | default(lxd_extracted_tarball_parent_path + '/' + _lxd_extracted_dir, true) }}"
    cmd: . "{{ lxd_source_go_env_vars_file_path }}" && make
  become: true
  environment:
    - CGO_CFLAGS: "{{ lxd_cgo_cflags }}"
    - CGO_LDFLAGS: "{{ lxd_cgo_ldflags }}"
    - CGO_LDFLAGS_ALLOW: "{{ lxd_cgo_ldflags_allow }}"
    - LD_LIBRARY_PATH: "{{ lxd_ld_library_path }}"
    - GOPATH: "{{ lxd_source_go_path }}"

- name: Reload the systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Stop the LXD service
  ansible.builtin.service:
    name: lxd
    enabled: true
    state: stopped
  become: true
