---
- name: Grab a LXD release tarball, and extract the archive
  ansible.builtin.unarchive:
    src: https://github.com/lxc/lxd/releases/download/lxd-{{ lxd_release_version }}/{{ _lxd_extracted_dir }}.tar.gz
    dest: "{{ lxd_extracted_tarball_path }}"
    remote_src: yes
  become: yes
  when: lxd_src_path | length == 0

- name: Build the LXD libraries
  ansible.builtin.shell:
    chdir: "{{ lxd_src_path | default(lxd_extracted_tarball_path + '/' + _lxd_extracted_dir, true) }}"
    cmd: . {{ _roots_home }}/.bashrc && make deps
  become: yes
  environment:
    - GOPATH: "{{ lxd_go_path }}"

- name: Build LXD
  ansible.builtin.shell:
    chdir: "{{ lxd_src_path | default(lxd_extracted_tarball_path + '/' + _lxd_extracted_dir, true) }}"
    cmd: . {{ _roots_home }}/.bashrc && make
  become: yes
  environment:
    - CGO_CFLAGS: "{{ lxd_cgo_cflags }}"
    - CGO_LDFLAGS: "{{ lxd_cgo_ldflags }}"
    - CGO_LDFLAGS_ALLOW: "{{ lxd_cgo_ldflags_allow }}"
    - LD_LIBRARY_PATH: "{{ lxd_ld_library_path }}"
    - GOPATH: "{{ lxd_go_path }}"
