---
# TODO(cavcrosby): sysvinit's init script directly invokes the daemon binary vs
# indirectly accessing the daemon binary via the wrapper. I also wish to reflect
# the same changes here.
- name: Create a LXD service unit file
  ansible.builtin.copy:
    dest: /etc/systemd/system/lxd.service
    mode: "644"
    content: |
      [Unit]
      Description=Linux Container Daemon

      [Service]
      Type=exec
      ExecStart={{ lxd_wrapper_path }} --group {{ lxd_access_group }}
      ExecStop={{ lxd_wrapper_path }} shutdown

      [Install]
      WantedBy=multi-user.target
  become: yes
  notify:
    - Save the current iptables rules
