---
- name: Create a LXD service unit file
  ansible.builtin.copy:
    dest: /etc/systemd/system/lxd.service
    mode: "644"
    content: |
      [Unit]
      Description=Linux Container Daemon

      [Service]
      Type=exec
      ExecStart={{ lxd_go_path }}/bin/lxd --group {{ lxd_access_group }}
      ExecStop={{ lxd_go_path }}/bin/lxd shutdown
      Environment=LD_LIBRARY_PATH={{ lxd_ld_library_path }}

      [Install]
      WantedBy=multi-user.target
  become: yes
  notify:
    - Save the current iptables rules
