[project]
name = "cavcrosby.general"
version = "1.0.0"
description = "A personal collection of reusable Ansible units"
requires-python = ">=3.10,<3.11"

[[authors]]
name = "Conner Crosby"
email = "cavcrosby@gmail.com"

[license]
file = "./LICENSE"
