---
- name: Reload the systemd daemon for jenkins_system_user's user services
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
  become: yes
  become_user: "{{ jenkins_system_user }}"
