---
- name: Create the container's Docker network
  community.docker.docker_network:
    name: "{{ container_network }}"
    ipam_config:
      - subnet: "{{ container_bridge_ipv4_subnet }}"
        iprange: "{{ container_bridge_ipv4_subnet }}"
        gateway: "{{ container_bridge_ipv4_addr }}"
    driver_options:
      com.docker.network.bridge.name: "{{ container_network }}"
  notify:
    - Restart Docker
  when: create_container_network

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Deploy a jenkins-base container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: cavcrosby/jenkins-{{ image_to_deploy }}:{{ image_tag }}
    published_ports:
      - "{{ jenkins_port_mapping }}"
      - "{{ jenkins_agents_port_mapping }}"
    cpus: "{{ container_cpus }}"
    memory: "{{ container_memory }}"
    volumes: "{{ container_volume }}"
    networks:
      - name: "{{ container_network }}"
        ipv4_address: "{{ container_ipv4_address }}"
    env:
      JENKINS_URL: "{{ jenkins_url }}"
      JENKINS_ADMIN_ID: "{{ jenkins_admin_id }}"
      JENKINS_ADMIN_PASSWORD: "{{ jenkins_admin_password }}"
      JENKINS_ADMIN_FULLNAME: "{{ jenkins_admin_fullname }}"
      JENKINS_ADMIN_EMAIL: "{{ jenkins_admin_email }}"
      JENKINS_ADMIN_EMAIL_SECRET: "{{ jenkins_admin_email_secret }}"
      SMTP_SERVER_ADDR: "{{ smtp_server_addr }}"
      JENKINS_GITHUB_CREDENTIAL_ID: "{{ jenkins_github_credential_id }}"
      JENKINS_GITHUB_CREDENTIAL_USERNAME: "{{ jenkins_github_credential_username }}"
      JENKINS_GITHUB_CREDENTIAL_SECRET: "{{ jenkins_github_credential_secret }}"
  # TODO(cavcrosby): add a prior task that ensures the docker image actually exists
  # before trying to make a container from it. I've had numerous times where I can't
  # remember why this task would fail and it would be for that reason.
  no_log: true
  when: image_to_deploy == "base"

# TODO(cavcrosby): release v1.4.1 to include the torkel image variant
- name: Deploy a jenkins-torkel container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: cavcrosby/jenkins-{{ image_to_deploy }}:{{ image_tag }}
    published_ports:
      - "{{ jenkins_port_mapping }}"
      - "{{ jenkins_agents_port_mapping }}"
    cpus: "{{ container_cpus }}"
    memory: "{{ container_memory }}"
    volumes: "{{ container_volume }}"
    networks:
      - name: "{{ container_network }}"
        ipv4_address: "{{ container_ipv4_address }}"
    env:
      JENKINS_URL: "{{ jenkins_url }}"
      JENKINS_ADMIN_ID: "{{ jenkins_admin_id }}"
      JENKINS_ADMIN_PASSWORD: "{{ jenkins_admin_password }}"
      JENKINS_ADMIN_FULLNAME: "{{ jenkins_admin_fullname }}"
      JENKINS_ADMIN_EMAIL: "{{ jenkins_admin_email }}"
      JENKINS_ADMIN_EMAIL_SECRET: "{{ jenkins_admin_email_secret }}"
      SMTP_SERVER_ADDR: "{{ smtp_server_addr }}"
      JENKINS_GITHUB_CREDENTIAL_ID: "{{ jenkins_github_credential_id }}"
      JENKINS_GITHUB_CREDENTIAL_USERNAME: "{{ jenkins_github_credential_username }}"
      JENKINS_GITHUB_CREDENTIAL_SECRET: "{{ jenkins_github_credential_secret }}"
      JENKINS_MAIN_NUM_EXECUTORS: "{{ jenkins_main_num_executors }}"
      JENKINS_AGENT_NAME1: "{{ jenkins_agent_name1 }}"
      JENKINS_AGENT_DESC1: "{{ jenkins_agent_desc1 }}"
      JENKINS_AGENT_NUM_EXECUTORS1: "{{ jenkins_agent_num_executors1 }}"
      JENKINS_AGENT_REMOTE_ROOT_DIR1: "{{ jenkins_agent_remote_root_dir1 }}"
  no_log: true
  when: image_to_deploy == "torkel"
