---
- name: Converge
  hosts: all

  tasks:
    - name: Create the molecule test file to use
      ansible.builtin.copy:
        dest: "{{ molecule_test_file_path }}"
        mode: "644"
        force: false
        content: |  # content from /usr/share/grub/default/grub
          # If you change this file, run 'update-grub' afterwards to update
          # /boot/grub/grub.cfg.
          # For full documentation of the options in this file, see:
          #   info -f grub -n 'Simple configuration'

          GRUB_DEFAULT=0
          GRUB_TIMEOUT_STYLE=hidden
          GRUB_TIMEOUT=0
          GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
          GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
          GRUB_CMDLINE_LINUX=""

          # Uncomment to enable BadRAM filtering, modify to suit your needs
          # This works with Linux (no patch required) and with any kernel that obtains
          # the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
          #GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

          # Uncomment to disable graphical terminal (grub-pc only)
          #GRUB_TERMINAL=console

          # The resolution used on graphical terminal
          # note that you can use only modes which your graphic card supports via VBE
          # you can see them in real GRUB with the command `vbeinfo'
          #GRUB_GFXMODE=640x480

          # Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
          #GRUB_DISABLE_LINUX_UUID=true

          # Uncomment to disable generation of recovery mode menu entries
          #GRUB_DISABLE_RECOVERY="true"

          # Uncomment to get a beep at grub start
          #GRUB_INIT_TUNE="480 440 1"

    - name: Add systemd.unified_cgroup_hierarchy=0 to GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.include_role:
        name: managed_lineinfile
      vars:
        managed_lineinfile_path: "{{ molecule_test_file_path }}"
        managed_lineinfile_regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
        managed_lineinfile_line: GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"
      loop: "{{ range(2) }}"

    - name: Set GRUB_INIT_TUNE to "480 440 1"
      ansible.builtin.include_role:
        name: managed_lineinfile
      vars:
        managed_lineinfile_path: "{{ molecule_test_file_path }}"
        managed_lineinfile_regexp: '^GRUB_INIT_TUNE="480 440 1"'
        managed_lineinfile_line: GRUB_INIT_TUNE="480 440 1"
