galaxy_info:
  role_name: jenkins_base_containers
  author: Conner Crosby
  description: Used to instantiate Jenkins containers that derive from the jenkins-base container
  license: BSD-3-Clause
  min_ansible_version: 2.12.1
